import type { Metadata } from "next"
import { M_PLUS_2 } from "next/font/google"
import { ParticleBackground } from "@/shared/ParticleBackground"
import "@/app/globals.css"

const mPlus2 = M_PLUS_2({
  weight: "400",
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja" className={`${mPlus2.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <main>{children}</main>
        <ParticleBackground />
      </body>
    </html>
  )
}
